import React from 'react';
import ReactDOM from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import './index.css';

// Register service worker — auto-updates when a new build is deployed.
// The SW is generated by vite-plugin-pwa at build time via Workbox.
registerSW({
  onNeedRefresh() {
    // A new version is available — in a future iteration this could
    // show a toast prompting the user to refresh.
    console.info('[PWA] New content available, will update on next reload.');
  },
  onOfflineReady() {
    console.info('[PWA] App ready to work offline.');
  },
});

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
