import React from 'react';
import ReactDOM from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import './index.css';


const cleanupLegacyServiceWorker = async () => {
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return;

  const cleanupKey = 'recipes-sw-cleanup-v1';
  if (localStorage.getItem(cleanupKey) === 'done') return;

  const registrations = await navigator.serviceWorker.getRegistrations();
  const origin = window.location.origin;

  await Promise.all(
    registrations
      .filter(registration => registration.scope.startsWith(origin))
      .map(registration => registration.unregister())
  );

  localStorage.setItem(cleanupKey, 'done');

  if (navigator.serviceWorker.controller) {
    window.location.reload();
  }
};

void cleanupLegacyServiceWorker();

// Register service worker — auto-updates when a new build is deployed.
// The SW is generated by vite-plugin-pwa at build time via Workbox.
registerSW({
  onNeedRefresh() {
    // A new version is available — in a future iteration this could
    // show a toast prompting the user to refresh.
    console.info('[PWA] New content available, will update on next reload.');
  },
  onOfflineReady() {
    console.info('[PWA] App ready to work offline.');
  },
});

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
